// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "gui.h"

void GUI::cb_DBG_i(Fl_Button*, void*) {
  DBG_cb();
}
void GUI::cb_DBG(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_DBG_i(o,v);
}

void GUI::cb_TestRot_i(Fl_Button*, void*) {
  TestRot_cb();
}
void GUI::cb_TestRot(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_TestRot_i(o,v);
}

void GUI::cb_TestRaster_i(Fl_Button*, void*) {
  TestRaster_cb();
}
void GUI::cb_TestRaster(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_TestRaster_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(265, 290, "GUI");
    uiw->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(15, 15, 225, 40, "DBG");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_DBG);
    } // Fl_Button* o
    { TestRot = new Fl_Button(20, 75, 215, 60, "Test Rotation");
      TestRot->down_box(FL_ENGRAVED_BOX);
      TestRot->color((Fl_Color)29);
      TestRot->selection_color((Fl_Color)137);
      TestRot->callback((Fl_Callback*)cb_TestRot);
    } // Fl_Button* TestRot
    { TestRaster = new Fl_Button(20, 150, 215, 60, "Test Rasterization");
      TestRaster->color((Fl_Color)38);
      TestRaster->selection_color((Fl_Color)137);
      TestRaster->callback((Fl_Callback*)cb_TestRaster);
    } // Fl_Button* TestRaster
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::TestRot_cb() {
  scene->TestRot();
}

void GUI::TestRaster_cb() {
	scene->TestRaster();
}
