// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
public:
  Fl_Button *TestRot;
private:
  void cb_TestRot_i(Fl_Button*, void*);
  static void cb_TestRot(Fl_Button*, void*);
public:
  Fl_Button *TestRaster;
private:
  void cb_TestRaster_i(Fl_Button*, void*);
  static void cb_TestRaster(Fl_Button*, void*);
public:
  void show();
  void DBG_cb();
  void TestRot_cb();
  void TestRaster_cb();
};
#endif
